### ISSUE TITLE
Inconsistent values

### ISSUE THREAD

**Issue by keystroke3** [TheWeirdDev/Bluetooth_Headset_Battery_Level#5]
I am trying to turn the script to a [Polybar](https://github.com/polybar/polybar) module so that I can have the battery information there. I have been successful in getting the values, and have made a few [changes](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/compare/master...keystroke3:master) so that it shows an icon instead of just the level. Problem is, the values are not consistent. When I run this, it keeps flipping between two values e.g. 70 and 80%. I do not fully understand how the script works, so a little elaboration may help me understand.

**Comment by TheWeirdDev** [comment]
That is pretty normal. Bluetooth headsets send the battery level in multiples of 10, for example if the actual level is 73% it might say it is 70 or 80. That's why it's not accurate sometime and gives different values.
It's better not to run the script too often and let the battery level change over a period of time to get a better result.

**Comment by keystroke3** [comment]
Ah, I see. I made a change in the script that makes it check every 5 min. In the version I showed you, I was testing it in a shell loop that cycled pretty fast. In it, it kept flipping so fast I thought it was a bug. Thanks anyway. You might consider submitting the script to [Polybar-scripts](https://github.com/polybar/polybar-scripts). I can do a pull request if you like.

**Comment by TheWeirdDev** [comment]
No problem. You can submit your fork. This one is just suitable for command line users.
